export const SELECT_ASSIGNMENT = 'SELECT_ASSIGNMENT';
export const DESELECT_ASSIGNMENT = 'DESELECT_ASSIGNMENT';
export const REMOVE_ASSIGNMENT = 'REMOVE_ASSIGNMENT';


export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const ADD_FAILED_ACTION = 'ADD_FAILED_ACTION';
export const REMOVE_FAILED_ACTION = 'REMOVE_FAILED_ACTION';
