export const API_SUFFIXES = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR'
};

export const API_ACTION_TYPES = {
  SPLIT_BID_PENDING: 'SPLIT_BID_PENDING',
  SPLIT_BID_SUCCESS: 'SPLIT_BID_SUCCESS',
  SPLIT_BID_ERROR: 'SPLIT_BID_ERROR',

  ADD_COMMENT_PENDING: 'ADD_COMMENT_PENDING',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_ERROR: 'ADD_COMMENT_ERROR',

  LOAD_ASSIGNMENTS_PENDING: 'LOAD_ASSIGNMENTS_PENDING',
  LOAD_ASSIGNMENTS_SUCCESS: 'LOAD_ASSIGNMENTS_SUCCESS',
  LOAD_ASSIGNMENTS_ERROR: 'LOAD_ASSIGNMENTS_ERROR',

  LOAD_ASSIGNMENT_PENDING: 'LOAD_ASSIGNMENT_PENDING',
  LOAD_ASSIGNMENT_SUCCESS: 'LOAD_ASSIGNMENT_SUCCESS',
  LOAD_ASSIGNMENT_ERROR: 'LOAD_ASSIGNMENT_ERROR',

  SET_ASSIGNMENT_STATUS_PENDING: 'SET_ASSIGNMENT_STATUS_PENDING',
  SET_ASSIGNMENT_STATUS_SUCCESS: 'SET_ASSIGNMENT_STATUS_SUCCESS',
  SET_ASSIGNMENT_STATUS_ERROR: 'SET_ASSIGNMENT_STATUS_ERROR'
};

export const ActionRegex = new RegExp(`(.*)(${API_SUFFIXES.SUCCESS}|${API_SUFFIXES.ERROR}|${API_SUFFIXES.PENDING})$`);
