export const SPLIT_BID_PENDING = 'SPLIT_BID_PENDING';
export const SPLIT_BID_SUCCESS = 'SPLIT_BID_SUCCESS';
export const SPLIT_BID_ERROR = 'SPLIT_BID_ERROR';

export const ADD_COMMENT_PENDING = 'ADD_COMMENT_PENDING';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

export const LOAD_ASSIGNMENT_PENDING = 'LOAD_ASSIGNMENT_PENDING';
export const LOAD_ASSIGNMENT_SUCCESS = 'LOAD_ASSIGNMENT_SUCCESS';
export const LOAD_ASSIGNMENT_ERROR = 'LOAD_ASSIGNMENT_ERROR';
